version: '3.7'
services:
    postgres:
        container_name: postgres
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
        volumes:
            - ../pg_data:/data/postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        container_name: airflow
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Sequential
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ../dags:/usr/local/airflow/dags
            - ../data_dir:/usr/local/airflow/data_dir/
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
